---
# geerlingguy stuff
downloads: ~/.ansible-downloads/

homebrew_installed_packages:
  - hub
  - httpie
  - ssh-copy-id

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - docker
  - dropbox
  - google-chrome

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
gem_packages: []
npm_packages: []
pip_packages: []

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

# my stuff
xdg_config_home: "~/.config"
xdg_cache_home: "~/.cache"
xdg_data_home: "~/.local/share"
xdg_bin_home: "~/.local/bin"

dotfiles: "~/.dotfiles"
dotfiles_data: "{{ xdg_data_home }}/dotfiles"

zdotdir: "{{ xdg_config_home }}/zsh"
zplug_home: "{{ xdg_cache_home }}/zplug"
# enabled_topics: all

# enabled_topics:
#   - shell/zsh
#   - shell/tmux

# topics:
#   editor:
#     - name: vim
#       state: present
#       config:
#         path: editor/vim
#         brew_formulas:
#           - vim
#     - name: emacs
#       state: present
#       config:
#         path: editor/emacs
#         brew_taps:
#           - d12frosted/emacs-plus
#         brew_formulas:
#           - name: emacs-plus
#             # install_options: without-spacemacs-icon
#   shell:
#     - name: zsh
#       state: present
#       config:
#         path: shell/zsh
#         brew_formulas:
#           - zsh
#           - fzf
#           - ripgrep
#         links:
#           - src: .zshrc
#             dest: "{{ zdotdir }}/"
#           - src: .zshenv
#             dest: "{{ zdotdir }}/"
#     - name: tmux
#       state: present
#       config:
#         path: shell/tmux
#         brew_formulas:
#           - tmux
#     - name: git
#       state: present
#       config:
#         path: shell/git
#         links:
#           - src: something
#             dest: somewhere
# topics:
#   editor:
#     - name: vim
#       enabled: yes
#       brew_formulas:
#         - vim
#     - name: emacs
#       enabled: yes
#       brew_taps:
#         - d12frosted/emacs-plus
#       brew_formulas:
#         - name: emacs_plus
#           install_options: without-spacemacs-icon
#   shell:
#     - name: zsh
#       enabled: no
#       brew_formulas:
#         - zsh
#         - fzf
#         - ripgrep
#     - name: tmux
#       enabled: yes
#       brew_formulas:
#         - tmux
