---
- hosts: mac

  vars_files:
    - default.config.yml

  # This is always overwritten by the dotfile config.yml
  # TODO: Find a way to make use of it to speed up CI
  pre_tasks:
    - name: allow local overrides
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: eliasnorrby.dotfiles
      tags: ["dotfiles"]
  # - role: geerlingguy.mas
  #   when: mas_installed_apps
  #   tags: ['mas']

  tasks:
    # TODO: Scope this properly. Now, it's possible to disable zsh in
    # dotfiles/config.yml and still have the zplug tasks trigger.
    - import_tasks: tasks/zplug.yml
      tags: zplug
    - import_tasks: tasks/doom-emacs.yml
      tags: doom-emacs
    - import_tasks: tasks/set-variables.yml
    - include_role:
        role: geerlingguy.homebrew
      tags: never,do_homebrew
    - include_role:
        role: geerlingguy.mas
      tags: never,do_mas
