---
- hosts: mac

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: allow local overrides
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    # - role: geerlingguy.homebrew
    #   tags: ['homebrew']

    - role: eliasnorrby.dotfiles
      tags: ["dotfiles"]

  # - role: geerlingguy.mas
  #   when: mas_installed_apps
  #   tags: ['mas']

  tasks:
    # TODO: Scope this properly. Now, it's possible to disable zsh in
    # dotfiles/config.yml and still have the zplug tasks trigger.
    - import_tasks: tasks/zplug.yml
      tags: zplug
    # - import_tasks: tasks/set-variables.yml
    #   tags: link
    # - import_tasks: tasks/homebrew-test.yml
    #   tags: link
