---
- name: check if hammerspoon_home is configured
  command: defaults read org.hammerspoon.Hammerspoon MJConfigFile
  failed_when: false
  changed_when: false
  register: mjconfigfile
- name: write hammerspoon_home with defaults
  command: defaults write org.hammerspoon.Hammerspoon MJConfigFile "{{ hammerspoon_home }}/init.lua"
  when: mjconfigfile.stdout != (hammerspoon_home | replace('~',ansible_user_dir) + "/init.lua")
