---
- set_fact:
    enabled_topics: "{{ q('dict', topics) | map(attribute='value') | list | flatten | selectattr('state', 'equalto', 'present') | list }}"

- debug:
    var: enabled_topics
    verbosity: 1

- set_fact:
    brew_formulas: "{{ enabled_topics | selectattr('brew_formulas', 'defined') | map(attribute='brew_formulas') | list | flatten | unique }}"

- debug:
    var: brew_formulas
    verbosity: 1

# so that you can have
# - name: emacs-plus
#   options: commented
- set_fact:
    brew_formulas_no_options: "{{ brew_formulas | selectattr('name', 'undefined') | list}}"
    brew_formulas_options: "{{ brew_formulas | selectattr('name', 'defined') | list }}"

- debug:
    var: brew_formulas_options
    verbosity: 1

- debug:
    var: brew_formulas_no_options
    verbosity: 1

- name: Ensure configured homebrew packages are installed
  block:
    - homebrew:
        name: "{{ brew_formulas_no_options }}"
        state: present
    - homebrew:
        name: "{{ item.name | default(item) }}"
        install_options: "{{ item.install_options | default(omit) }}"
        state: present
      loop: "{{ brew_formulas_options }}"
