---
# Prepare vaiables for geerlingguy.homebrew
- debug:
    var: topics
    verbosity: 1

- debug:
    var: present_topics
    verbosity: 1

- set_fact:
    homebrew_installed_packages: "{{ present_topics | selectattr('config.brew_formulas', 'defined') | map(attribute='config.brew_formulas') | list | flatten | unique }}"
    homebrew_uninstalled_packages: "{{ absent_topics | selectattr('config.brew_formulas', 'defined') | map(attribute='config.brew_formulas') | list | flatten | unique }}"
    homebrew_taps: "{{ present_topics | selectattr('config.brew_taps', 'defined') | map(attribute='config.brew_taps') | list | flatten | unique }}"
    homebrew_cask_apps: "{{ present_topics | selectattr('config.brew_casks', 'defined') | map(attribute='config.brew_casks') | list | flatten | unique }}"
    homebrew_cask_uninstalled_apps: "{{ absent_topics | selectattr('config.brew_casks', 'defined') | map(attribute='config.brew_casks') | list | flatten | unique }}"

- debug:
    var: homebrew_installed_packages
    verbosity: 1

- debug:
    var: homebrew_uninstalled_packages
    verbosity: 1

- debug:
    var: homebrew_taps
    verbosity: 1

- debug:
    var: homebrew_cask_apps
    verbosity: 1

- debug:
    var: homebrew_cask_uninstalled_apps
    verbosity: 1
# - set_fact:
#     topic_links: "{{ enabled_topics | selectattr('links', 'defined') | map(attribute='links') | list | flatten | unique }}"

# - debug:
#     var: topic_links
#     verbosity: 1

# - set_fact:
#     topics_with_links: "{{ enabled_topics | selectattr('links', 'defined') | list }}"

# - debug:
#     var: topics_with_links

# - include_tasks: link-stuff.yml
#   loop: "{{ enabled_topics | selectattr('links', 'defined') | list }}"
#   loop_control:
#     loop_var: topic
